# template 

# - id: DOI
#   type: paper / book
#   description: 
#   date: 2020-12-4
#   image: 
#   buttons:
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/random-github/
#     - type: website
#       link: https://randomlink.com/
#   tags:
#     - tag1 
#     - tag2
#   repo: username/repo

- id: doi:10.1080/14742837.2021.1967736
  type: paper
  description: Building on efforts to connect social movement and memory studies, this article examines if the massive size and transnational nature of the February 2003 anti-war protests resulted in an equally widely shared and transnational form of memory.
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/csms20.v022.i02
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/random-github/
    - type: website
      link: https://randomlink.com/
  tags:
    - Transnational contention
    - Transnational memory
    - Digital humanities
  repo: username/repo

- id: doi:10.1017/9781108565080.007
  type: book
  description: An overview of computational work in dialectology
  authors:
  - Nerbonne J.
  - Heeringa W.
  - Prokic J.
  - Wieling M.
  image: https://assets.cambridge.org/97811084/29351/cover/9781108429351.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/random-github/
    - type: website
      link: https://randomlink.com/
  tags:
    - Computational linguistics
    - Dialectology
    - Literature review
  repo: username/repo