---
date: 2023-02-16
title: Deep Learning Workshop with Aron van de Pol
author: Aron van de Pol
categories:
  - Workshop
  - Deep learning
---
# Deep Learning for beginners workshop

Deep-learning has been used in many recent applications You’ve likely seen use cases such as Stable diffusion, DALL-E image generation, ChatGPT text generation, image classification and, object detection in self-driving cars. Deep-learning is also gaining popularity in the humanities, even beyond NLP uses.

In this workshop we are teaching humanities students & researchers how to train neural networks using PyTorch, thereby allowing them to eventually use this for their own research interests. Meaning this course is heavily focused onto the practical side of neural network programming.

The main focus revolves around visual data, but the basics taught in this course are equally important for language or audio related deep learning:

1. *Tensors*: The powerhouse of Deep Learning
2. *Harnessing* the power of randomness: Training Loops & Lineair regression using Neural Networks (2 March)
3. *Classification issues and Non-Linearity*
4. *Unleashing the Potential of Images as Data*
5. *Conquering image classification with Convolutional Neural Networks*
6. *Leveraging the power of Transfer Learning*: Harnessing the knowledge of other datasets to reach new heights. With this knowledge, you can continue to teach yourself further in expanding beyond the focus of images onto other forms of data such a text (NLP tasks).

### Location
Digital Lab, P.J. Veth 1.07 Time: TBD

### Availability
