---
title: Congratulations Justin!
author: Admin
date: 2024-08-15
categories:
  - News
---

# Huge Congrats to Justin!

We are happy to announce that [Justin](/members/Justin-Yeung.html) has been accepted as a PhD student at the [Complex Connection Lab, Network Science Institute, Northeastern University](http://barabasilab.com/)! This is an incredible achievement for Justin and a testament to his hard work and dedication.

## About Justin's Research Interests

Justin's research focuses on developing and applying techniques from network theory and information theory to study collective human behaviors. He aims to understand how people interact with each other and share information through opinion dynamics and information spreading mechanisms. His work has already been published in reputable journals such as AI & Society, Journalism Studies, and top international conferences.

Justin is finalizing his MSc in Social Data Science at the Oxford Internet Institute, University of Oxford, after completing this he will start his PhD trajectory.

## Best Wishes!

We are all excited to see Justin's journey unfold and wish him every success in his PhD studies! Congratulations once again, Justin!
