---
title: Computational Linguistics in the Netherlands (CLIN 34)
author: Jelena Prokic
date: 2024-03-28
categories:
  - Conference
  - Computational Linguistics
---
# Computational Linguistics in the Netherlands (CLIN 34)

The 34th Meeting of Computational Linguistics in The Netherlands ([CLIN 34](https://clin34.leidenuniv.nl/)), organized by the Leiden University Centre for Linguistics (LUCL), in collaboration with the Leiden Institute of Advanced Computer Science (LIACS), and the Leiden University Centre for Digital Humanities (LUCDH), is set to be held on August 30, 2024 in the Lipsius building of Leiden University, Leiden, The Netherlands.

### Call for abstracts

Abstracts describing work on any aspect of computational linguistics / natural language processing (finished or in progress), are welcome for submission at CLIN34. Submissions must be written in English and must be submitted through [this web form](https://docs.google.com/forms/d/1G2Ee1LUfQdmh2xQz8T46YcR1BXUMuB4q4iuAKq9sp8Q/viewform?edit_requested=true). Please provide all information requested in the form.

The submission deadline is May 15th 2024 and notifications of acceptance will be sent out on June 15th 2024. Authors of accepted abstracts will have the opportunity to submit a full paper after the conference to CLIN Journal. 
